// Seed data for the `talents` Firestore collection, matching Master_Schema.html's
// Talent DB schema. Per the automation-scope cutback: only stat-changing talents
// get statModifiers, and only talents requiring a skill/characteristic pick at
// purchase get skillChoice/characteristicChoice (needed for DISPLAY of what was
// picked, not automation). Everything else is pure `rules` text, same as a
// paper sheet. poolModifiers/resultModifiers/scalingBonus/requirement/etc. from
// the original Master Schema design are still valid schema fields — just
// unpopulated here by deliberate choice, not because they don't apply. Future-you:
// this file was written AFTER the automation-scope cutback decision, so don't
// read the sparse structured fields as an oversight — see Implementation
// Guide's Key Decisions Log for the full reasoning.

export interface TalentDoc {
  id: string
  name: string
  tier: 1 | 2 | 3 | 4 | 5
  activation: 'Passive' | 'Action' | 'Maneuver' | 'Incidental' | 'Incidental (Out of Turn)'
  ranked: boolean
  limit: 'None' | 'Per Round' | 'Per Encounter' | 'Per Session'
  rules: string
  prerequisite?: string // id of required talent
  statModifiers?: { stat: string; amount: number }[] // per rank
  skillChoice?: { count: number; restriction?: string; grantsCareer?: boolean; fixedSkills?: string[] }
  characteristicChoice?: { count: number }
}

export const TALENTS: TalentDoc[] = [
  // ---- Tier 1 ----
  { id: 'bought-info', name: 'Bought Info', tier: 1, activation: 'Action', ranked: false, limit: 'None',
    rules: "Pay currency (50x the check's difficulty) to auto-succeed a Knowledge check with one success instead of rolling, GM permitting." },
  { id: 'clever-retort', name: 'Clever Retort', tier: 1, activation: 'Incidental (Out of Turn)', ranked: false, limit: 'Per Encounter',
    rules: "Add two setback dice to another character's social skill check, even outside your turn." },
  { id: 'defensive-sysops', name: 'Defensive Sysops', tier: 1, activation: 'Passive', ranked: false, limit: 'None',
    rules: "When defending a computer system you own/programmed, or when someone hacks it, add a setback die to their check. You're automatically aware of any intrusion if you have access to the system at the time." },
  { id: 'desperate-recovery', name: 'Desperate Recovery', tier: 1, activation: 'Passive', ranked: false, limit: 'None',
    rules: 'If your strain is over half your threshold at the end of an encounter, heal two extra strain during normal recovery.' },
  { id: 'duelist', name: 'Duelist', tier: 1, activation: 'Passive', ranked: false, limit: 'None',
    rules: 'Add a boost die to melee checks while engaged with exactly one opponent; add a setback die instead while engaged with three or more.' },
  { id: 'durable', name: 'Durable', tier: 1, activation: 'Passive', ranked: true, limit: 'None',
    rules: 'Reduces the result rolled on any Critical Injury by 10 per rank (minimum 1).' },
  { id: 'forager', name: 'Forager', tier: 1, activation: 'Passive', ranked: false, limit: 'None',
    rules: 'Removes up to two setback dice from checks to find food, water, or shelter; such checks take half the normal time.' },
  { id: 'grit', name: 'Grit', tier: 1, activation: 'Passive', ranked: true, limit: 'None',
    rules: '+1 Strain Threshold per rank.',
    statModifiers: [{ stat: 'strainThreshold', amount: 1 }] },
  { id: 'hamstring-shot', name: 'Hamstring Shot', tier: 1, activation: 'Action', ranked: false, limit: 'Per Round',
    rules: 'Make a ranged attack against a non-vehicle target; on a hit, halve the damage (before soak) and immobilize the target until the end of their next turn.' },
  { id: 'jump-up', name: 'Jump Up', tier: 1, activation: 'Incidental', ranked: false, limit: 'Per Round',
    rules: 'Stand up from prone or seated as a free incidental, on your turn.' },
  { id: 'knack-for-it', name: 'Knack For It', tier: 1, activation: 'Passive', ranked: true, limit: 'None',
    rules: 'Pick a skill (not combat skills) — remove one setback die from checks with it. Each further rank lets you pick two more skills for the same benefit.',
    skillChoice: { count: 1, restriction: 'no combat or magic skills', grantsCareer: false } },
  { id: 'know-somebody', name: 'Know Somebody', tier: 1, activation: 'Incidental', ranked: true, limit: 'Per Session',
    rules: 'When attempting to purchase a legally available item, reduce its rarity by one per rank.' },
  { id: 'lets-ride', name: "Let's Ride", tier: 1, activation: 'Incidental', ranked: false, limit: 'Per Round',
    rules: 'Mount, dismount, or reposition within a vehicle as a free incidental; suffer no damage and land on your feet from a short fall off a vehicle or mount.' },
  { id: 'one-with-nature', name: 'One With Nature', tier: 1, activation: 'Incidental', ranked: false, limit: 'None',
    rules: 'In the wilderness, use Survival instead of Discipline or Cool to recover strain at the end of an encounter.' },
  { id: 'parry', name: 'Parry', tier: 1, activation: 'Incidental (Out of Turn)', ranked: true, limit: 'None',
    rules: 'When hit by a melee attack, spend 3 strain to reduce the damage by two plus your ranks (once per hit). Requires wielding a melee weapon.' },
  { id: 'proper-upbringing', name: 'Proper Upbringing', tier: 1, activation: 'Incidental', ranked: true, limit: 'None',
    rules: 'In polite settings, spend strain (up to your ranks) to add that many advantage to a social check.' },
  { id: 'quick-draw', name: 'Quick Draw', tier: 1, activation: 'Incidental', ranked: false, limit: 'Per Round',
    rules: "Draw or holster a weapon as a free incidental; also lowers a weapon's Prepare rating by one." },
  { id: 'quick-strike', name: 'Quick Strike', tier: 1, activation: 'Passive', ranked: true, limit: 'None',
    rules: "Add a boost die per rank to combat checks against targets who haven't acted yet this encounter." },
  { id: 'rapid-reaction', name: 'Rapid Reaction', tier: 1, activation: 'Incidental (Out of Turn)', ranked: true, limit: 'None',
    rules: 'Spend strain (up to your ranks) to add that many success to a Vigilance or Cool Initiative check.' },
  { id: 'second-wind', name: 'Second Wind', tier: 1, activation: 'Incidental', ranked: true, limit: 'Per Encounter',
    rules: 'Heal strain equal to your ranks.' },
  { id: 'surgeon', name: 'Surgeon', tier: 1, activation: 'Passive', ranked: true, limit: 'None',
    rules: 'When you make a Medicine check to heal wounds, the target heals one additional wound per rank.' },
  { id: 'swift', name: 'Swift', tier: 1, activation: 'Passive', ranked: false, limit: 'None',
    rules: 'Move through difficult terrain at full speed with no extra maneuver cost.' },
  { id: 'toughened', name: 'Toughened', tier: 1, activation: 'Passive', ranked: true, limit: 'None',
    rules: '+2 Wound Threshold per rank.',
    statModifiers: [{ stat: 'woundThreshold', amount: 2 }] },
  { id: 'unremarkable', name: 'Unremarkable', tier: 1, activation: 'Passive', ranked: false, limit: 'None',
    rules: 'Others add a setback die to checks made to find or identify you in a crowd.' },

  // ---- Tier 2 ----
  { id: 'basic-military-training', name: 'Basic Military Training', tier: 2, activation: 'Passive', ranked: false, limit: 'None',
    rules: 'Athletics, Ranged (Heavy), and Resilience become career skills for you.',
    skillChoice: { count: 0, fixedSkills: ['athletics', 'ranged-heavy', 'resilience'], grantsCareer: true } },
  { id: 'berserk', name: 'Berserk', tier: 2, activation: 'Maneuver', ranked: false, limit: 'Per Encounter',
    rules: "Until the encounter ends or you're incapacitated: add a boost and two advantage dice to your melee checks, but opponents add a boost die to attacks against you, and you cannot make ranged attacks. Suffer 6 strain when the effect ends." },
  { id: 'coordinated-assault', name: 'Coordinated Assault', tier: 2, activation: 'Maneuver', ranked: true, limit: 'None',
    rules: 'Once per turn: allies engaged with you (up to your Leadership ranks) gain a boost die on combat checks until your next turn. Range extends per rank beyond the first.' },
  { id: 'counteroffer', name: 'Counteroffer', tier: 2, activation: 'Action', ranked: false, limit: 'Per Session',
    rules: 'Opposed Negotiation vs. Discipline against a non-boss enemy in medium range; success staggers them, and a strong success can temporarily turn them friendly.' },
  { id: 'daring-aviator', name: 'Daring Aviator', tier: 2, activation: 'Incidental', ranked: true, limit: 'None',
    rules: 'Before a Driving or Piloting check, convert boost results already rolled into an equal number of triumph, up to your ranks.' },
  { id: 'defensive-stance', name: 'Defensive Stance', tier: 2, activation: 'Maneuver', ranked: true, limit: 'Per Round',
    rules: 'Spend strain (up to your ranks) to upgrade the difficulty of melee attacks against you that many times until your next turn.' },
  { id: 'defensive-sysops-improved', name: 'Defensive Sysops (Improved)', tier: 2, activation: 'Incidental', ranked: false, limit: 'None',
    rules: "Requires Defensive Sysops. Converts that talent's setback die into two threat on the intruder's check instead.",
    prerequisite: 'defensive-sysops' },
  { id: 'dual-wielder', name: 'Dual Wielder', tier: 2, activation: 'Maneuver', ranked: false, limit: 'None',
    rules: 'Reduces the difficulty of your next two-weapon combined check this turn by one.' },
  { id: 'fan-the-hammer', name: 'Fan the Hammer', tier: 2, activation: 'Incidental', ranked: false, limit: 'Per Encounter',
    rules: 'Add the Auto-fire quality to a pistol for one check; the weapon then runs out of ammo afterward.' },
  { id: 'heightened-awareness-talent', name: 'Heightened Awareness', tier: 2, activation: 'Passive', ranked: false, limit: 'None',
    rules: 'Allies within short range get a boost die on Perception/Vigilance; engaged allies get two boost dice instead.' },
  { id: 'inspiring-rhetoric', name: 'Inspiring Rhetoric', tier: 2, activation: 'Action', ranked: false, limit: 'None',
    rules: 'Make a Leadership check; each success heals one strain to an ally in short range, each advantage heals an extra strain to someone already helped.' },
  { id: 'inventor', name: 'Inventor', tier: 2, activation: 'Incidental', ranked: true, limit: 'None',
    rules: "Add a boost die per rank when building or modifying gear; can also attempt to recreate devices you've only heard described." },
  { id: 'lucky-strike', name: 'Lucky Strike', tier: 2, activation: 'Incidental', ranked: false, limit: 'None',
    rules: 'Pick a characteristic when bought. After a successful combat hit, spend a Story Point to add bonus damage equal to your rating in that characteristic.',
    characteristicChoice: { count: 1 } },
  { id: 'scathing-tirade', name: 'Scathing Tirade', tier: 2, activation: 'Action', ranked: false, limit: 'None',
    rules: 'Make a Coercion check; each success deals one strain to an enemy in short range, each advantage deals an extra strain to someone already hit.' },
  { id: 'side-step', name: 'Side Step', tier: 2, activation: 'Action', ranked: true, limit: 'Per Round',
    rules: 'Spend strain (up to your ranks) to upgrade the difficulty of ranged attacks against you that many times until your next turn.' },

  // ---- Tier 3 ----
  { id: 'animal-companion', name: 'Animal Companion', tier: 3, activation: 'Passive', ranked: true, limit: 'None',
    rules: 'Bond with a small approved animal that follows and assists you; higher ranks allow a larger companion.' },
  { id: 'barrel-roll', name: 'Barrel Roll', tier: 3, activation: 'Incidental (Out of Turn)', ranked: false, limit: 'None',
    rules: 'While piloting a small starfighter/aircraft, spend 3 vehicle strain to reduce incoming ranged damage by your Piloting ranks.' },
  { id: 'distinctive-style', name: 'Distinctive Style', tier: 3, activation: 'Incidental', ranked: false, limit: 'None',
    rules: 'Before a Computers check to hack a system, add two success and two advantage to the results.' },
  { id: 'dodge', name: 'Dodge', tier: 3, activation: 'Incidental (Out of Turn)', ranked: true, limit: 'None',
    rules: 'Like Side Step, but works against any attack (not just ranged) targeting you.' },
  { id: 'eagle-eyes', name: 'Eagle Eyes', tier: 3, activation: 'Incidental', ranked: false, limit: 'Per Encounter',
    rules: "Increase your weapon's range by one band for a single attack." },
  { id: 'field-commander', name: 'Field Commander', tier: 3, activation: 'Action', ranked: false, limit: 'None',
    rules: 'Make a Leadership check; success lets a number of allies equal to your Presence each spend 1 strain to take a free maneuver out of turn.' },
  { id: 'forgot-to-count', name: 'Forgot to Count?', tier: 3, activation: 'Incidental (Out of Turn)', ranked: false, limit: 'None',
    rules: "Spend two advantage from an enemy's ranged attack roll to make their weapon run out of ammo." },
  { id: 'full-throttle', name: 'Full Throttle', tier: 3, activation: 'Action', ranked: false, limit: 'None',
    rules: "Make a Hard Piloting/Driving check while driving or flying; success increases the vehicle's top speed by one for rounds equal to your Cunning." },
  { id: 'grenadier', name: 'Grenadier', tier: 3, activation: 'Incidental', ranked: true, limit: 'None',
    rules: "Spend a Story Point instead of advantage to trigger a weapon's Blast quality, even on a miss; treat grenades as medium range." },
  { id: 'heroic-will', name: 'Heroic Will', tier: 3, activation: 'Incidental (Out of Turn)', ranked: false, limit: 'None',
    rules: 'Pick two characteristics when bought. Spend a Story Point to ignore Critical Injury penalties on checks using either characteristic for the rest of the encounter.',
    characteristicChoice: { count: 2 } },
  { id: 'inspiring-rhetoric-improved', name: 'Inspiring Rhetoric (Improved)', tier: 3, activation: 'Passive', ranked: false, limit: 'None',
    rules: 'Requires Inspiring Rhetoric. Allies healed by your Inspiring Rhetoric also gain a boost die on checks for a number of rounds equal to your Leadership ranks.',
    prerequisite: 'inspiring-rhetoric' },
  { id: 'natural', name: 'Natural', tier: 3, activation: 'Incidental', ranked: false, limit: 'Per Session',
    rules: 'Pick two skills when bought. Reroll one check made with either of those skills.',
    skillChoice: { count: 2 } },
  { id: 'painkiller-specialization', name: 'Painkiller Specialization', tier: 3, activation: 'Passive', ranked: true, limit: 'None',
    rules: 'Painkillers you administer heal one extra wound per rank (still capped at five uses per day).' },
  { id: 'parry-improved', name: 'Parry (Improved)', tier: 3, activation: 'Incidental (Out of Turn)', ranked: false, limit: 'None',
    rules: 'Requires Parry. After successfully using Parry, spend a triumph or three advantage from the attacker\'s roll to automatically hit them back with a Brawl or Melee weapon.',
    prerequisite: 'parry' },
  { id: 'rapid-archery', name: 'Rapid Archery', tier: 3, activation: 'Maneuver', ranked: false, limit: 'None',
    rules: 'Suffer 2 strain; your bow gains the Linked quality equal to your Ranged ranks for your next attack this turn.' },
  { id: 'scathing-tirade-improved', name: 'Scathing Tirade (Improved)', tier: 3, activation: 'Passive', ranked: false, limit: 'None',
    rules: 'Requires Scathing Tirade. Enemies hit by your Scathing Tirade also take a setback die on checks for a number of rounds equal to your Coercion ranks.',
    prerequisite: 'scathing-tirade' },

  // ---- Tier 4 ----
  { id: 'cant-we-talk-about-this', name: "Can't We Talk About This?", tier: 4, activation: 'Action', ranked: false, limit: 'None',
    rules: 'Opposed Charm/Deception vs. Discipline against a non-boss enemy in medium range; success stops them attacking you until their next turn (spendable successes extend it further).' },
  { id: 'deadeye', name: 'Deadeye', tier: 4, activation: 'Incidental', ranked: false, limit: 'None',
    rules: 'After rolling a ranged Critical Injury, spend 2 strain to swap it for a different Critical Injury of the same severity.' },
  { id: 'defensive', name: 'Defensive', tier: 4, activation: 'Passive', ranked: true, limit: 'None',
    rules: '+1 melee and ranged Defense per rank.',
    statModifiers: [{ stat: 'meleeDefense', amount: 1 }, { stat: 'rangedDefense', amount: 1 }] },
  { id: 'defensive-driving', name: 'Defensive Driving', tier: 4, activation: 'Passive', ranked: true, limit: 'None',
    rules: 'Increases a vehicle you pilot\'s defense by one per rank.' },
  { id: 'enduring', name: 'Enduring', tier: 4, activation: 'Passive', ranked: true, limit: 'None',
    rules: '+1 Soak per rank.',
    statModifiers: [{ stat: 'soak', amount: 1 }] },
  { id: 'field-commander-improved', name: 'Field Commander (Improved)', tier: 4, activation: 'Passive', ranked: false, limit: 'None',
    rules: 'Requires Field Commander. Now affects allies equal to twice your Presence, and a strong success lets one ally take a full action instead of a maneuver.',
    prerequisite: 'field-commander' },
  { id: 'how-convenient', name: 'How Convenient!', tier: 4, activation: 'Action', ranked: false, limit: 'Per Session',
    rules: 'A Hard Mechanics check makes a device involved in the current scene conveniently break down.' },
  { id: 'inspiring-rhetoric-supreme', name: 'Inspiring Rhetoric (Supreme)', tier: 4, activation: 'Incidental', ranked: false, limit: 'None',
    rules: 'Requires Inspiring Rhetoric (Improved). Spend 1 strain to use Inspiring Rhetoric as a maneuver instead of an action.',
    prerequisite: 'inspiring-rhetoric-improved' },
  { id: 'mad-inventor', name: 'Mad Inventor', tier: 4, activation: 'Action', ranked: false, limit: 'Per Session',
    rules: 'A Mechanics check (difficulty set by rarity) jury-rigs a working equivalent of an item from scrap.' },
  { id: 'overcharge', name: 'Overcharge', tier: 4, activation: 'Action', ranked: false, limit: 'Per Encounter',
    rules: 'A Hard Mechanics check temporarily doubles the bonus from one of your cybernetic implants until the encounter ends.' },
  { id: 'scathing-tirade-supreme', name: 'Scathing Tirade (Supreme)', tier: 4, activation: 'Incidental', ranked: false, limit: 'None',
    rules: 'Requires Scathing Tirade (Improved). Spend 1 strain to use Scathing Tirade as a maneuver instead of an action.',
    prerequisite: 'scathing-tirade-improved' },

  // ---- Tier 5 ----
  { id: 'dedication', name: 'Dedication', tier: 5, activation: 'Passive', ranked: true, limit: 'None',
    rules: '+1 to a characteristic of your choice per rank (max 5); the same characteristic cannot be boosted twice.',
    characteristicChoice: { count: 1 } },
  { id: 'indomitable', name: 'Indomitable', tier: 5, activation: 'Incidental (Out of Turn)', ranked: false, limit: 'Per Encounter',
    rules: 'Spend a Story Point to avoid being incapacitated until the end of your next turn, even past your wound or strain threshold.' },
  { id: 'master', name: 'Master', tier: 5, activation: 'Incidental', ranked: false, limit: 'Per Round',
    rules: "Pick a skill when bought. Spend 2 strain to lower that skill's next check difficulty by two (minimum Easy).",
    skillChoice: { count: 1 } },
  { id: 'overcharge-improved', name: 'Overcharge (Improved)', tier: 5, activation: 'Passive', ranked: false, limit: 'None',
    rules: 'Requires Overcharge. Spend two advantage or a triumph on an Overcharge check to take one additional action immediately.',
    prerequisite: 'overcharge' },
  { id: 'ruinous-repartee', name: 'Ruinous Repartee', tier: 5, activation: 'Action', ranked: false, limit: 'Per Encounter',
    rules: 'Opposed Charm/Coercion vs. Discipline on one target in medium range; success deals strain to them (twice your Presence, plus one per success) and heals you the same amount.' },
]